apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: TCC-cluster
  region: us-east-1

managedNodeGroups:
  - name: private-nodes
    instanceType: t3.medium
    minSize: 2
    maxSize: 4
    
    desiredCapacity: 2 # La crearea clusterului, se crează 2 noduri
    privateNetworking: true # Nodurile create sunt ascunse de internet(private)
    volumeSize: 20
    iam:
      withAddonPolicies: # Permisiuni automate pentru funcții extra
        imageBuilder: true
        autoScaler: true
        cloudWatch: true