apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hybrid-orchestrator
webhooks:
  - name: orchestrator.tcc.local
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]

    objectSelector:
      matchExpressions:
        - key: app
          operator: NotIn
          values: ["hybrid-webhook", "hybrid-dispatcher"]
          
    clientConfig:
      caBundle: 
      service:
        name: hybrid-webhook-service
        namespace: default
        path: "/mutate"