#Role-Based Access Control (RBAC) pentru Dispatcher
# Acest fișier definește un ServiceAccount, un ClusterRole și un ClusterRole
# Binding pentru a acorda permisiuni Dispatcher-ului să interacționeze cu resursele Kubernetes


apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatcher-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dispatcher-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services", "namespaces"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dispatcher-binding
subjects:
  - kind: ServiceAccount
    name: dispatcher-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: dispatcher-role
  apiGroup: rbac.authorization.k8s.io